# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.

# Setup
title:               "FangXing"
tagline:             ''
description:         'FangXing'
url:                 http://fffx.github.io
baseurl:             ''
google_analytics: "UA-120686214-1"

# About/contact
author:
  name:              fangxing
  email:             ppohiv3s7@mozmail.comkk

social:
    name: Fang Xing
    links:
      - https://github.com/fffx
      - https://telegram.me/fangxing

# Custom vars
version:             1.0.0
github: fffx
host_ip: "192.168.56.2"



relative_permalinks: false

plugins:
  - jekyll-archives
  - jekyll-livereload
  - jekyll-seo-tag
host: 0.0.0.0
incremental: true
