# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.

# Setup
title:               "FangXing"
tagline:             ''
description:         'FangXing'
url:                 http://fffx.github.io
baseurl:             ''

# About/contact
author:
  name:              fangxing
  url:               https://twitter.com/xfangxing
  email:             fangxing204@gmail.com

# Custom vars
version:             1.0.0
github: fffx
host_ip: "192.168.56.2"


relative_permalinks: false

plugins:
  - jekyll-archives
  - jekyll-livereload
  - jekyll-seo-tag
host: 0.0.0.0
incremental: true
